### ISSUE TITLE
Use Storage facade in configuration?

### ISSUE THREAD

**Issue by gendronb** [spatie/laravel-directory-cleanup#11]
Hi,

First, as with all your projects, great work!

My question : is it be possible to use the Storage facade to target (local) directories? Such as 

```
Storage::disk('local_disk') => [
    'deleteAllOlderThanMinutes' => 60 * 24 * 7
]
```

As is, when running `php artisan clean:directories`, I get 

```
In laravel-directory-cleanup.php line 21:
  Class 'Storage' not found 
```
If I add `Use \Illuminate\Support\Facades\Storage as Storage;` I get 

```
In Facade.php line 218:
  A facade root has not been set.
```

**Comment by freekmurze** [comment]
No, that's not possible as the framework is not fully booted when the configuration files are being read.
