### ISSUE TITLE
Possibility of recursive delete?

### ISSUE THREAD

**Issue by rehmatworks** [spatie/laravel-directory-cleanup#14]
Can we make it so it will delete the directories and files as well? i.e. if we use a temporary directory to store files and directories there and want to clean that temporary directory, then this deletes only files as of now. Is there a way to delete the directories as well? Thanks for your great tools.

**Comment by freekmurze** [comment]
Seems like a bug to me that the directories are not deleted. I'd accept a PR that fixes this.

**Comment by leroy** [comment]
@freekmurze what if a directory is older than the configured amount of minutes but contains files that do not?

**Comment by freekmurze** [comment]
I'd only delete directories if there are no files in them anymore.
