### ISSUE TITLE
Hidden files are not deleted

### ISSUE THREAD

**Issue by bluec** [spatie/laravel-directory-cleanup#27]
Any hidden files in the specified directory are not deleted, even with the default `DeleteEverything` policy. In fact it's currently impossible to write a policy that does delete hidden files.

Note that hidden files in any subdirectory are deleted so this is inconsistent behaviour (see #26)

**Comment by freekmurze** [comment]
Feel free to submit a PR with tests that fixes this

**Comment by freekmurze** [comment]
I'm going to keep this simple and threat this as a bugfix release, thanks!
