### ISSUE TITLE
Installation Error from Composer

### ISSUE THREAD

**Issue by Bronco84** [spatie/laravel-directory-cleanup#29]
I am a little new when it comes to maintaining composer packages, so I apologize if this seems obvious, but I want to make sure I understand the problem. When I try and install this package with composer it returns the following error:

`Problem 1
    - Installation request for spatie/laravel-directory-cleanup ^1.3 -> satisfiable by spatie/laravel-directory-cleanup[1.3.0].
    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - spatie/laravel-directory-cleanup 1.3.0 requires illuminate/support ~5.8.0 -> satisfiable by illuminate/support[v5.8.0, v5.8.2].
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].`

So if I'm reading this correctly, does it mean that the illuminate/support package I have isn't a high enough version? At this time I have laravel ^5.7 listed in composer json file, but I don't have illuminate/support listed at all. Doesn't laravel require it? Shouldn't it be listed based on that? When pacakges have requirements, don't those get "pulled in" automatically? Again, I know this seems like basic stuff but I'm trying to understand these concepts so any clarification would be appreciated!

**Comment by freekmurze** [comment]
Try running  `spatie/laravel-directory-cleanup`. Composer will select the right version.

**Comment by Bronco84** [comment]
Yeah that's the command I used. It begins installing the latest version and eventually returns the error I posted.
