### ISSUE TITLE
Files are not deleted

### ISSUE THREAD

**Issue by shawnfromportland** [spatie/laravel-directory-cleanup#30]
I am simply trying to use this to delete old files from the storage directory. I am on Laravel 5.6. I run clean:directories and get a successful message:
`$ php artisan clean:directories                                                                                         Cleaning directories...                                                                                                                                   All done!`
however no files in the storage directory are modified. 

my config is as follows:
```
'/home/vagrant/code/myApp/storage' => [
            'deleteAllOlderThanMinutes' => 60,
        ],
```
I have also tried using just 'storage' as the folder key name.

no files are deleted. (my storage folder contains many files older than 60 minutes)

**Comment by freekmurze** [comment]
The tests indicate that the package is working as intended, so this might be caused by your environment.

Could you please PR a failing test for me to look at?

**Comment by shawnfromportland** [comment]
@freekmurze after further stackoverflow investigation i believe it was an unexpected configuration in my filesystem.php file. I ended up writing my own solution since what I needed was so simple.
thank you!
