### ISSUE TITLE
Empty folders is not deleted

### ISSUE THREAD

**Issue by danielbrodin** [spatie/laravel-directory-cleanup#33]
I have tried the package on 3 environments, my local environment, a dev server and the production server. On all three old files were removed, but only my local environment manage to actually delete the empty folders. Do you have any idea why this is?

I can't manage to find any errors, but that could be a miss I guess.

I'm using version `1.2.4` since I haven't been able to update laravel yet.

```php
'directories' => [
    'storage/app/temp' => [
        'deleteAllOlderThanMinutes' => 60 * 24 * 7,
    ],
],
```

**Comment by freekmurze** [comment]
Our tests indicate the package is working as intended. Should you find an error in our package, let us know.
