### ISSUE TITLE
Wrong console output if no files are deleted

### ISSUE THREAD

**Issue by briavers** [spatie/laravel-directory-cleanup#38]
When no files are deleted the console says 
Cleaning directories...
Deleted 30 file(s) from storage/app/public/tmp/uploads.
Deleted 0 directory(ies) from storage/app/public/tmp/uploads.
All done!

```
<?php

use Spatie\DirectoryCleanup\Policies\DeleteEverything;

return [

    'directories' => [

        /*
         * Here you can specify which directories need to be cleanup. All files older than
         * the specified amount of minutes will be deleted.
         */


        'storage/app/public/tmp/uploads' => [
            'deleteAllOlderThanMinutes' => 30,
        ],

    ],

    /*
     * If a file is older than the amount of minutes specified, a cleanup policy will decide if that file
     * should be deleted. By default every file that is older that the specified amount of minutes
     * will be deleted.
     *
     * You can customize this behaviour by writing your own clean up policy.  A valid policy
     * is any class that implements `Spatie\DirectoryCleanup\Policies\CleanupPolicy`.
     */
    'cleanup_policy' => DeleteEverything::class,
];
```
If i put `'deleteAllOlderThanMinutes' => 60,` then the same is said only saying deleted 60 files

I don't need the console output so is no big issue for me but just wanted to let you know

**Comment by voydz** [comment]
Hey,

the issue might be related to https://github.com/spatie/laravel-directory-cleanup/pull/36. This PR was merged (which seems to fix your issue). But it has not been released to packagist, yet.

It would be awesome if some guys from spatie could do it? @freekmurze maybe? :)

best regards

**Comment by freekmurze** [comment]
Fix is now tagged. 👍
