### ISSUE TITLE
Allow to specify a Policy for each path

### ISSUE THREAD

**Issue by rodrigopedra** [spatie/laravel-directory-cleanup#41]
Would you be open to allow to specify a Policy for each path?

My use case is that I have some files to be kept in different directories that could be deleted from others.

For example, in a directory that preprocess bulk inserts to a SQL Server database I need to keep `.fmt` files which hold the format configuration to be used by the `bcp` CLI tool. But in a directory that accepts temporary uploads it is fine to delete such files.

I can workaround now by adding if clauses to my custom policy to check for the file path, but it would be cleaner to have a custom policy for such folders and defer to a standard one if not specified.

I could try sending a PR if that would be desirable.

Thanks!

**Comment by freekmurze** [comment]
We like to keep this package as simple as possible.

The feature would add complexity that most don't need.

Feel free to fork our package 👍

**Comment by rodrigopedra** [comment]
No problem, I thought about that before trying a PR.

Thanks for the response, and thanks for this package. Have a nice day =)
